using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class StationListItem : PanelContainer
{
    public sealed class ViewState(
        NetEntity stationEntity,
        string stationName,
        string stationSubtext,
        string stationDescription,
        bool selected,
        string? iconPath)
    {
        public string StationName { get; } = stationName;
        public string StationSubtext { get; } = stationSubtext;
        public string StationDescription { get; } = stationDescription;
        public NetEntity StationEntity { get; } = stationEntity;

        public bool Selected { get; set; } = selected;

        public string IconPath { get; } = iconPath ?? "";
    }

    public StationListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);

        StationName.Text = state.StationName;
        StationSubtext.Text = state.StationSubtext;

        // Disallow repeated selection of same station that does UI reloads.
        StationButton.Disabled = state.Selected;

        if (state.IconPath.Length > 0)
        {
            // Check if this is an RSI path (contains .rsi/)
            // Aurora Song: Support RSI state paths in iconPath without throwing exceptions.
            if (state.IconPath.Contains(".rsi/"))
            {
                var parts = state.IconPath.Split(".rsi/");
                if (parts.Length == 2)
                {
                    var rsiPath = parts[0] + ".rsi";
                    var stateName = parts[1];

                    // Resolve RSI resource and ensure the state exists before assigning.
                    // This avoids relying on exception flow and keeps the lobby UI resilient.
                    var cache = IoCManager.Resolve<IResourceCache>();
                    if (cache.TryGetResource<RSIResource>(new ResPath(rsiPath), out var rsiRes))
                    {
                        var rsi = rsiRes.RSI;
                        if (rsi.TryGetState(stateName, out var rsiState))
                        {
                            StationIcon.Texture = rsiState.Frame0;
                        }
                    }
                }
            }
            else
            {
                // Regular texture path
                StationIcon.TexturePath = state.IconPath;
            }
        }
    }
}
