- type: entity
  id: ThrusterMedicMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: SLE thruster machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: ThrusterMedic
    requirements:
      Capacitor: 3
    stackRequirements:
      Steel: 5

- type: entity
  id: ASTechFabSLECircuitboard
  parent: SecurityTechFabCircuitboard
  name: SLE techfab machine board
  description: A machine printed circuit board for an SLE techfab.
  components:
    - type: Sprite
      sprite: _AS/Objects/Misc/module.rsi
      state: sle
    - type: MachineBoard
      prototype: ASTechFabSLE

- type: entity
  id: SLETechFabCircuitboard
  parent: ASTechFabSLECircuitboard
  suffix: Deprecated
